### ISSUE TITLE
Improved generated protocol documentation

### ISSUE THREAD

**Issue by codingchili** [codingchili/chili-core#252]
- [x] use YAML instead of JSON for readability.
- [x] map route path to route info for readability (the info is nested)

Good:
```yaml
---
description: "A simple highscore API."
routes:
  update:
    description: "Updates the highscore entries with the given entry."
    model:
      score: "java.lang.Integer"
      player: "java.lang.String"
    roles:
    - "PUBLIC"
  list:
    description: "Returns a list of the current highscore selection."
    roles:
    - "PUBLIC"
```

Bad:
```json
{
  "model" : { },
  "text" : "A simple highscore API.",
  "routes" : [ {
    "model" : {
      "score" : "java.lang.Integer",
      "player" : "java.lang.String"
    },
    "description" : "Updates the highscore entries with the given entry.",
    "role" : [ "PUBLIC" ],
    "name" : "update"
  }, {
    "model" : { },
    "description" : "Returns a list of the current highscore selection.",
    "role" : [ "PUBLIC" ],
    "name" : "list"
  } ],
  "status" : "ACCEPTED",
  "target" : "api",
  "route" : "documentation"
}
```

- [x] empty objects
- [x] json is not readable enough
- [x] order of fields are not intuitive
- [x] response headers should be removed
